development:
  adapter: postgresql
  encoding: unicode
  database: moneytrackrails_development
  pool: 5
  username: postgres
  password: rs0
  template: template0
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: moneytrackrails_test
  pool: 5
  username: postgres
  password: rs0
  template: template0
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: moneytrackrails_production
  pool: 5
  username: postgres
  password: rs0
  template: template0
  host: localhost